### ISSUE TITLE
repo_type参数问题

### ISSUE THREAD

**Issue by yanglu7** [XuekaiChen/ChatWithDoc#2]
windows环境部署了chatglm2-6b,api测试通过，
运行 demo_pro.py时提示这个问题，是因为我环境问题吗？是否有哪里配置兼容的问题
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/chenxuekai/bert-sentence/text2vec-large-chinese'. Use `repo_type` argument if needed.

**Comment by XuekaiChen** [comment]
这个地方是要下载一个词向量编码模型，用于问题与文档中内容的相似度匹配。我用的是[text2vec](https://huggingface.co/GanymedeNil/text2vec-large-chinese)，你可以下一个一样的模型，然后在配置文件[config.yaml](https://github.com/XuekaiChen/ChatWithDoc/blob/master/config.yaml)中标明路径即可

**Comment by yanglu7** [comment]
Task exception was never retrieved
future: <Task finished name='ino2nfyfy1k_4' coro=<Queue.process_events() done, defined at D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [''], 'event_dat...on_hash': 'ino2nfyfy1k'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [''], 'event_dat...on_hash': 'ino2nfyfy1k'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

这个问题您遇到过吗？启动提示成功，访问页面一直在计时读秒，隔一会发现控制台出现这个。我对AI了解比较少，想找个文件对话的可以私有化部署的项目测试一下效果，太难了。。。哈哈

**Comment by yanglu7** [comment]
Task exception was never retrieved
future: <Task finished name='ino2nfyfy1k_4' coro=<Queue.process_events() done, defined at D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [''], 'event_dat...on_hash': 'ino2nfyfy1k'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\gradio\queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "D:\anaconda\envs\chatwithdoce\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [''], 'event_dat...on_hash': 'ino2nfyfy1k'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

这个问题您遇到过吗？启动提示成功，访问页面一直在计时读秒，隔一会发现控制台出现这个。我对AI了解比较少，想找个文件对话的可以私有化部署的项目测试一下效果，太难了。。。哈哈
